services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: weather_forecaster_development
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - api_bundle:/usr/local/bundle
    env_file:
      - ./api/.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/weather_forecaster_development
    ports:
      - "3001:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:3001}
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  postgres_data:
  api_bundle:
  frontend_node_modules: 