services:
  - type: web
    name: weather-forecaster-api
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: weather-forecaster-db
          property: connectionString

databases:
  - name: weather-forecaster-db
    databaseName: weather_forecaster_production
    user: weather_forecaster
    plan: free # optional (defaults to starter) 